import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { ReactionForm } from "@/components/ReactionForm";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`relative ${inter.className}`}>
        {children}
        <ReactionForm />
      </body>
    </html>
  );
}
